.MODEL SMALL
.STACK 100H
.DATA
    CR EQU 0DH
    LF EQU 0AH
    MSG1  DB "ENTER A LOWER CASE NUMBER : $"
    MSG2  DB CR,LF,'THE UPPER CASE NUMBER IS : '
    CHAR  DB ?, '$'

.CODE
MAIN PROC
  ; INITIALIZE DS
    MOV AX , @DATA    ; GET DATA SEGMENT
    MOV DS , AX       ; INITIALIZE DATA SEGMENT

  ; PRINT USER PROMT
    LEA DX , MSG1     ; LOAD MESSAGE1 TO DX
    MOV AH , 09H      ; SET FUNCTION 09H
    INT 21H           ; DISPLAY MESSAGE1

  ; GET USER INPUT
    MOV AH , 01H      ; SET FUNCTION 01H INPUT
    INT 21H           ; GET A CHARACTER
    SUB AL , 20H      ; CONVERT TO UPPER CASE
    MOV CHAR , AL     ; SAVE CHARACTER IN CHAR

  ; PRINT RESULT
    LEA DX , MSG2     ; LOAD MESSAGE2 TO DX
    MOV AH , 09H      ; SET FUNCTION 09H
    INT 21H           ; DISPLAY MESSAGE2

  ; DOS EXIT
    MOV AH , 4CH      ; SET FUNCTION 4CH
    INT 21H           ; RETURN TO DOS
MAIN ENDP
END MAIN